### ISSUE TITLE
Too 💪

### ISSUE THREAD

**Issue by kivikakk** [ticky/postcss-stronk#3]
Every time I see this repo it just makes me wanna 💪.

Please advise.

**Comment by ticky** [comment]
This is an intended side-effect.

**Comment by kivikakk** [comment]
I feel like this should at least be documented :/

**Comment by ticky** [comment]
Documentation PRs are most welcome!

**Comment by kivikakk** [comment]
💪

**Comment by ticky** [comment]
Fixed by #5.
